apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finpro-blb-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
