apiVersion: v1
kind: Secret
metadata:
  name: blb-secret
  
data:
  DB_NAME: ZGV2X2JsYl9lbmM=
  DB_PASSWORD: dGVzdEAxMjM=
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTAuMjAuMzAuOTg6NTU1NS9kZXZfYmxiX2VuYz9zdHJpbmd0eXBlPXVuc3BlY2lmaWVk
  DB_USER_NAME: dGVzdA==
  DEPLOYMENT_NAMESPACE: ZmlucHJvLWJsYg==
  GATEWAY_URL: aHR0cHM6Ly9ibGJ0ZXN0LmRyb3NlYmxiLmNvbS5ucA==
  JWT_KEY: UkhRMFVraHFhbkZxVmxod1R6bHFaMFIwTkZKSWFtcHhhbFpZY0U4NWFtY0s=
  KAFKA_SERVER: bXkta2Fma2Eua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
type: Opaque
