apiVersion: apps/v1
kind: Deployment
metadata:
    name: finpro-blb-portal
    labels:
        app: finpro-blb-portal
spec:
    replicas: 1
    selector:
        matchLabels:
            app: finpro-blb-portal
    template:
        metadata:
            labels:
                app: finpro-blb-portal
        spec:
            containers:
                - name: finpro-blb-portal-pod
                  image: reg.citytech.global/finpulse/blb-portal-uat-nimb:UAT.2
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                      - containerPort: 443
                  resources:
                      limits:
                          cpu: 200m
                          memory: 256Mi
                      requests:
                          cpu: 100m
                          memory: 256Mi
                  livenessProbe:
                      tcpSocket:
                          port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3
                  readinessProbe:
                      tcpSocket:
                          port: 80
                      initialDelaySeconds: 5
                      periodSeconds: 5
                      timeoutSeconds: 5
