apiVersion: v1
kind: PersistentVolume
metadata:
    name: finpro-blb-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: microk8s-hostpath
  hostPath:
    path: /opt/blb

