apiVersion: apps/v1
kind: Deployment
metadata:
  name: finpro-blb
  namespace: blb-test
  labels:
    app: finpro-blb
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finpro-blb
  template:
    metadata:
      labels:
        app: finpro-blb

    spec:
      volumes:
        - name: finproblb
          persistentVolumeClaim:
            claimName: finpro-blb-pvc
      containers:
        - name: finpro-blb
          image: reg.citytech.global/finpulse/blb:UAT.19
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: JWT_KEY
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: DB_URL
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: DB_USER_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: DB_PASSWORD
            - name: KAFKA_SERVER
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: KAFKA_SERVER
            - name: DEPLOYMENT_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: DEPLOYMENT_NAMESPACE
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: blb-secret
                  key: GATEWAY_URL
            - name: JVM_OPTS
              value: '-XX:+UseContainerSupport -XX:MaxRAMPercentage=80'
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 400m
              memory: 500Mi
          volumeMounts:
            - name: finproblb
              mountPath: /opt/blb
          livenessProbe:
            httpGet:
              path: /v1/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            timeoutSeconds: 40
            periodSeconds: 40
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /v1/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            timeoutSeconds: 40
            periodSeconds: 40
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
