apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs
  
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  type: 
  archiveOnDelete: 'false'
reclaimPolicy: Delete
volumeBindingMode: Immediate
